# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# NeoForge Properties
# Check https://projects.neoforged.net/neoforged/neoforge for updates
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.84
loader_version_range=[4,)

# Parchment Mappings
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

# Mod Properties
mod_id=xercamusic
mod_name=Music Maker Mod
mod_license=GPL-3.0
mod_version=1.21.1-1.0.1
mod_group_id=xerca.xercamusic
mod_authors=xerca
mod_description=Music Maker Mod - Create and play music with various instruments in Minecraft
